# Generated by Django 3.1 on 2020-09-10 08:06

import applications.core.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='published', max_length=50, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, help_text='JPG. 400x400', null=True, upload_to=applications.core.models.PathAndRename('services/popular/photo'), verbose_name='Изображение')),
                ('link', models.URLField(max_length=300, verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'популярная услуга',
                'verbose_name_plural': 'популярные услуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='published', max_length=50, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-имя')),
                ('photo', models.ImageField(blank=True, help_text='JPG. 1040x500px', null=True, upload_to=applications.core.models.PathAndRename('services/service/photo'), verbose_name='Изображение')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Контент')),
                ('conclusion', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Контент (после прайса)')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.CharField(max_length=50, verbose_name='Стоимость')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'прайс',
                'verbose_name_plural': 'прайс',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='JPG. 1200px по большей стороне', upload_to=applications.core.models.PathAndRename('services/photo'), verbose_name='Изображение')),
                ('youtube_link', models.CharField(blank=True, help_text='Ссылка на YouTube', max_length=200, verbose_name='Ссылка на видео')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'медиа',
                'verbose_name_plural': 'медиа',
                'ordering': ['order'],
            },
        ),
    ]
