# Generated by Django 3.1 on 2020-09-13 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200913_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popular',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popular', to='services.service', verbose_name='Услуга'),
        ),
    ]
