# Generated by Django 3.1 on 2020-09-13 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200913_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popular',
            name='link',
        ),
    ]
