# Generated by Django 3.1 on 2020-09-10 08:06

import applications.core.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_1', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Контент (до галереи)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий (слева)')),
                ('content_2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Контент (после галереи)')),
            ],
            options={
                'verbose_name': 'о компании',
                'verbose_name_plural': 'о компании',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Первый контент')),
                ('content_2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Второй контент')),
            ],
            options={
                'verbose_name': 'главная страница',
                'verbose_name_plural': 'главная страница',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='published', max_length=50, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-имя')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'страница',
                'verbose_name_plural': 'статические страницы',
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, help_text='Например, site.com или localhost:8000', max_length=50, verbose_name='Имя сайта')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('phone_mobile', models.CharField(blank=True, max_length=50, verbose_name='Телефон (мобильный)')),
                ('phone_whatsapp', models.CharField(blank=True, help_text='Писать в формате "380661234567"', max_length=50, verbose_name='Whatsapp')),
                ('phone_viber', models.CharField(blank=True, help_text='Писать в формате "380661234567"', max_length=50, verbose_name='Viber')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('footer_address', models.TextField(blank=True, verbose_name='Адрес (подвал)')),
                ('map_link', models.CharField(blank=True, max_length=200, verbose_name='Ссылка на проезд к Офису')),
                ('social_facebook', models.CharField(blank=True, max_length=200, verbose_name='Facebook')),
                ('social_vkontakte', models.CharField(blank=True, max_length=200, verbose_name='Vkontakte')),
                ('social_instagram', models.CharField(blank=True, max_length=200, verbose_name='Instagram')),
                ('social_telegram', models.CharField(blank=True, max_length=200, verbose_name='Telegram')),
                ('site_title', models.CharField(max_length=200, verbose_name='Заголовок сайта')),
                ('site_description', models.TextField(verbose_name='Описание сайта')),
                ('site_photo', models.ImageField(blank=True, help_text='Загружать JPG 1200х630', upload_to=applications.core.models.PathAndRename('preference'), verbose_name='Изображение для шаринга')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Эл.почта')),
                ('email_appointment', models.TextField(blank=True, help_text='Каждый емэйл с новой строки', verbose_name='Емэйлы для заявок "Записаться на встречу"')),
            ],
            options={
                'verbose_name': 'настройки',
                'verbose_name_plural': 'настройки',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='published', max_length=50, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('title', models.TextField(verbose_name='Название')),
                ('photo', models.ImageField(help_text='JPG. 1400x700', upload_to=applications.core.models.PathAndRename('slide'), verbose_name='Изображение')),
                ('button_text', models.CharField(default='Узнать больше', max_length=50, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(max_length=200, verbose_name='Ссылка кнопки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'слайд',
                'verbose_name_plural': 'слайдер',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, help_text='Загружать JPG', upload_to=applications.core.models.PathAndRename('main/aboutphoto'), verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.about', verbose_name='О компании')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'фото',
                'ordering': ['order'],
            },
        ),
    ]
