# Generated by Django 3.1 on 2020-09-12 09:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='comment_en',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий (слева)'),
        ),
        migrations.AddField(
            model_name='about',
            name='comment_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий (слева)'),
        ),
        migrations.AddField(
            model_name='about',
            name='content_1_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Контент (до галереи)'),
        ),
        migrations.AddField(
            model_name='about',
            name='content_1_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Контент (до галереи)'),
        ),
        migrations.AddField(
            model_name='about',
            name='content_2_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент (после галереи)'),
        ),
        migrations.AddField(
            model_name='about',
            name='content_2_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент (после галереи)'),
        ),
        migrations.AddField(
            model_name='index',
            name='content_1_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый контент'),
        ),
        migrations.AddField(
            model_name='index',
            name='content_1_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый контент'),
        ),
        migrations.AddField(
            model_name='index',
            name='content_2_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Второй контент'),
        ),
        migrations.AddField(
            model_name='index',
            name='content_2_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Второй контент'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='preference',
            name='address_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='preference',
            name='address_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='preference',
            name='footer_address_en',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес (подвал)'),
        ),
        migrations.AddField(
            model_name='preference',
            name='footer_address_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес (подвал)'),
        ),
        migrations.AddField(
            model_name='preference',
            name='site_description_en',
            field=models.TextField(null=True, verbose_name='Описание сайта'),
        ),
        migrations.AddField(
            model_name='preference',
            name='site_description_ru',
            field=models.TextField(null=True, verbose_name='Описание сайта'),
        ),
        migrations.AddField(
            model_name='preference',
            name='site_title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок сайта'),
        ),
        migrations.AddField(
            model_name='preference',
            name='site_title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок сайта'),
        ),
        migrations.AddField(
            model_name='slide',
            name='button_text_en',
            field=models.CharField(default='Узнать больше', max_length=50, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='slide',
            name='button_text_ru',
            field=models.CharField(default='Узнать больше', max_length=50, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='slide',
            name='title_en',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='slide',
            name='title_ru',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
    ]
