# Generated by Django 3.1 on 2020-12-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_popular_link'),
        ('main', '0002_auto_20200912_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='published', max_length=50, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('youtube_link', models.CharField(help_text='Ссылка на YouTube', max_length=200, verbose_name='Ссылка на видео')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('services', models.ManyToManyField(blank=True, related_name='videos', to='services.Service', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'главная страница - видео',
                'verbose_name_plural': 'главная страница - видео',
                'ordering': ['order'],
            },
        ),
    ]
