# Generated by Django 3.1 on 2020-09-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя, фамилия')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('time', models.CharField(blank=True, max_length=50, verbose_name='Время')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'запись на встречу',
                'ordering': ['-created'],
            },
        ),
    ]
